# Generated by Django 4.0.6 on 2022-08-01 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('duration_from', models.DateField()),
                ('duration_to', models.DateField()),
                ('name_of_institute', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Experiecne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('responsibilities', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('works_as', models.CharField(choices=[('Freelancer', 'Freelancer'), ('UI/UX Designer', 'UI/UX Designer'), ('Django Developer', 'Django Developer')], max_length=50)),
                ('age', models.PositiveBigIntegerField()),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('freelance', models.BooleanField(default=False)),
                ('degree', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('facebook_link', models.URLField(max_length=100)),
                ('instagram_link', models.URLField(max_length=100)),
                ('linkedin_link', models.URLField(max_length=100)),
                ('github_link', models.URLField(max_length=100)),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
            ],
        ),
    ]
