# Generated by Django 4.0.6 on 2022-08-01 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Experiecne',
            new_name='Experience',
        ),
    ]
