# Generated by Django 4.0.6 on 2022-08-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_profile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='freelance',
            field=models.CharField(choices=[('Availabe', 'Availabe'), ('Unavailabe', 'Unavailabe')], max_length=50),
        ),
    ]
