# Generated by Django 4.0.6 on 2022-08-01 05:27

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_profile_freelance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='works_as',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Freelancer', 'Freelancer'), ('UI/UX Designer', 'UI/UX Designer'), ('Django Developer', 'Django Developer')], max_length=50),
        ),
    ]
