# Generated by Django 4.0.6 on 2022-09-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_profile_age_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='name_of_organization',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
