# Generated by Django 4.0.6 on 2022-09-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_experience_name_of_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='time_period',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
    ]
