# Generated by Django 4.0.6 on 2022-09-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackEndSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('knowledge', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='Skill',
            new_name='FrontEndSkill',
        ),
    ]
