# Generated by Django 4.1.5 on 2023-01-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_alter_education_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='duration_from',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='duration_to',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='responsibilities',
            field=models.TextField(blank=True, null=True),
        ),
    ]
